CREATE TABLE comments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    is_deleted        BOOLEAN                                 NOT NULL,
    content           VARCHAR(2000)                           NOT NULL,
    post_id           BIGINT                                  NOT NULL,
    author_id         BIGINT                                  NOT NULL,
    parent_comment_id BIGINT,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

CREATE TABLE file_attachments
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at        TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    is_deleted        BOOLEAN                                 NOT NULL,
    original_filename VARCHAR(255)                            NOT NULL,
    stored_filename   VARCHAR(255)                            NOT NULL,
    file_path         VARCHAR(500)                            NOT NULL,
    content_type      VARCHAR(100)                            NOT NULL,
    file_size         BIGINT                                  NOT NULL,
    uploader_id       BIGINT                                  NOT NULL,
    post_id           BIGINT,
    CONSTRAINT pk_file_attachments PRIMARY KEY (id)
);

CREATE TABLE likes
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    post_id    BIGINT,
    comment_id BIGINT,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE marketplace_items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    is_deleted  BOOLEAN                                 NOT NULL,
    title       VARCHAR(100)                            NOT NULL,
    description VARCHAR(2000)                           NOT NULL,
    price       DECIMAL(19, 2)                          NOT NULL,
    status      VARCHAR(255)                            NOT NULL,
    seller_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_marketplace_items PRIMARY KEY (id)
);

CREATE TABLE posts
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN                                 NOT NULL,
    title      VARCHAR(100)                            NOT NULL,
    content    VARCHAR(1000)                           NOT NULL,
    state      VARCHAR(255)                            NOT NULL,
    author_id  BIGINT,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    is_deleted    BOOLEAN                                 NOT NULL,
    username      VARCHAR(60)                             NOT NULL,
    name          VARCHAR(60),
    bio           VARCHAR(2000),
    password_hash VARCHAR(255)                            NOT NULL,
    email         VARCHAR(120),
    phone_number  VARCHAR(15),
    role          VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE likes
    ADD CONSTRAINT uc_80ca0085c9eb6b5ca25673a0c UNIQUE (user_id, comment_id);

ALTER TABLE likes
    ADD CONSTRAINT uc_88d5108ea5e46ca11e828b43e UNIQUE (user_id, post_id);

ALTER TABLE file_attachments
    ADD CONSTRAINT uc_file_attachments_stored_filename UNIQUE (stored_filename);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone_number UNIQUE (phone_number);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_marketplace_created_at ON marketplace_items (created_at);

CREATE INDEX idx_marketplace_status ON marketplace_items (status);

CREATE INDEX idx_posts_created_at ON posts (created_at);

CREATE INDEX idx_posts_state ON posts (state);

CREATE INDEX idx_users_email ON users (email);

CREATE INDEX idx_users_phone ON users (phone_number);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

CREATE INDEX idx_comments_author ON comments (author_id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_PARENT_COMMENT FOREIGN KEY (parent_comment_id) REFERENCES comments (id);

CREATE INDEX idx_comments_parent ON comments (parent_comment_id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);

CREATE INDEX idx_comments_post ON comments (post_id);

ALTER TABLE file_attachments
    ADD CONSTRAINT FK_FILE_ATTACHMENTS_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);

CREATE INDEX idx_file_post ON file_attachments (post_id);

ALTER TABLE file_attachments
    ADD CONSTRAINT FK_FILE_ATTACHMENTS_ON_UPLOADER FOREIGN KEY (uploader_id) REFERENCES users (id);

CREATE INDEX idx_file_uploader ON file_attachments (uploader_id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_COMMENT FOREIGN KEY (comment_id) REFERENCES comments (id);

CREATE INDEX idx_likes_comment ON likes (comment_id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_POST FOREIGN KEY (post_id) REFERENCES posts (id);

CREATE INDEX idx_likes_post ON likes (post_id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_likes_user ON likes (user_id);

ALTER TABLE marketplace_items
    ADD CONSTRAINT FK_MARKETPLACE_ITEMS_ON_SELLER FOREIGN KEY (seller_id) REFERENCES users (id);

CREATE INDEX idx_marketplace_seller ON marketplace_items (seller_id);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

CREATE INDEX idx_posts_author ON posts (author_id);