CREATE TABLE marketplace_item_favorites
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN                                 NOT NULL,
    user_id    BIGINT                                  NOT NULL,
    item_id    BIGINT                                  NOT NULL,
    CONSTRAINT pk_marketplace_item_favorites PRIMARY KEY (id)
);

ALTER TABLE marketplace_items
    ADD COLUMN category VARCHAR(60);

ALTER TABLE users
    ADD COLUMN profile_picture_id BIGINT;

ALTER TABLE marketplace_item_favorites
    ADD CONSTRAINT uc_9b8adaceaa11b6ed736daaafd UNIQUE (user_id, item_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_profile_picture UNIQUE (profile_picture_id);

ALTER TABLE marketplace_item_favorites
    ADD CONSTRAINT FK_MARKETPLACE_ITEM_FAVORITES_ON_ITEM FOREIGN KEY (item_id) REFERENCES marketplace_items (id);

CREATE INDEX idx_marketplace_favorites_item ON marketplace_item_favorites (item_id);

ALTER TABLE marketplace_item_favorites
    ADD CONSTRAINT FK_MARKETPLACE_ITEM_FAVORITES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

CREATE INDEX idx_marketplace_favorites_user ON marketplace_item_favorites (user_id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_PROFILE_PICTURE FOREIGN KEY (profile_picture_id) REFERENCES file_attachments (id);

CREATE INDEX idx_users_profile_picture ON users (profile_picture_id);