CREATE TABLE lab_flags
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at   TIMESTAMP WITHOUT TIME ZONE,
    is_deleted   BOOLEAN                                 NOT NULL,
    lab_id       VARCHAR(64)                             NOT NULL,
    task_id      VARCHAR(128)                            NOT NULL,
    flag_value   VARCHAR(255)                            NOT NULL,
    seed_context VARCHAR(255),
    CONSTRAINT pk_lab_flags PRIMARY KEY (id)
);

CREATE TABLE lab_task_progress
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    is_deleted    BOOLEAN                                 NOT NULL,
    lab_id        VARCHAR(64)                             NOT NULL,
    task_id       VARCHAR(128)                            NOT NULL,
    status        VARCHAR(32)                             NOT NULL,
    points_awarded INTEGER                                NOT NULL,
    completed_at  TIMESTAMP WITHOUT TIME ZONE,
    evidence      VARCHAR(255),
    CONSTRAINT pk_lab_task_progress PRIMARY KEY (id)
);

ALTER TABLE lab_flags
    ADD CONSTRAINT uc_lab_flags_lab_task UNIQUE (lab_id, task_id);

ALTER TABLE lab_flags
    ADD CONSTRAINT uc_lab_flags_flag_value UNIQUE (flag_value);

ALTER TABLE lab_task_progress
    ADD CONSTRAINT uc_lab_task_progress_lab_task UNIQUE (lab_id, task_id);

CREATE INDEX idx_lab_flags_lab ON lab_flags (lab_id);

CREATE INDEX idx_lab_task_progress_lab ON lab_task_progress (lab_id);