CREATE TABLE lab_hint_reveals
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN                                 NOT NULL,
    lab_id     VARCHAR(64)                             NOT NULL,
    task_id    VARCHAR(128)                            NOT NULL,
    hint_id    VARCHAR(128)                            NOT NULL,
    CONSTRAINT pk_lab_hint_reveals PRIMARY KEY (id)
);

ALTER TABLE lab_hint_reveals
    ADD CONSTRAINT uc_lab_hint_reveals_lab_task_hint UNIQUE (lab_id, task_id, hint_id);

CREATE INDEX idx_lab_hint_reveals_lab_task ON lab_hint_reveals (lab_id, task_id);